//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOCIOS
    {
        public int ID { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDOS { get; set; }
        public string CEDULA { get; set; }
        public string FOTO { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONO { get; set; }
        public string SEXO { get; set; }
        public Nullable<int> EDAD { get; set; }
        public Nullable<System.DateTime> FECHA_NACIMIENTO { get; set; }
        public string DATOS_MEMBRESIA { get; set; }
        public string LUGAR_TRABAJO { get; set; }
        public string DIRECCION_OFICINA { get; set; }
        public string TEL_OFICINA { get; set; }
        public string ESTADO { get; set; }
        public Nullable<System.DateTime> FECHA_INGRESO { get; set; }
        public Nullable<System.DateTime> FECHA_SALIDA { get; set; }
    }
}
